# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: 'windows-latest'

steps:
- task: AzureCLI@2
  displayName: 'Upload Prod'
  inputs:
    azureSubscription: "シグマコンサルティング(eee9046c-f7c0-4e03-98e0-3660ae9224fc)"
    scriptType: "ps"
    scriptLocation: "inlineScript"
    inlineScript: 'az storage blob upload-batch -d $(container) -s $(Build.SourcesDirectory) --account-name $(storagename) --account-key $(accountkey)'
    